# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
schema = "school_trips_driver"

[migrations_directory]
dir = "./migrations"
